# Generated by Django 5.2.1 on 2025-06-28 04:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoElectronico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=4)),
                ('numero', models.IntegerField()),
                ('receptor_tipo_doc', models.CharField(default='6', max_length=1)),
                ('receptor_numero_doc', models.CharField(max_length=15)),
                ('receptor_razon_social', models.CharField(max_length=100)),
                ('receptor_direccion', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('isc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('icbper', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('xml_content', models.TextField(blank=True, null=True)),
                ('xml_firmado', models.TextField(blank=True, null=True)),
                ('hash_digest', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Firma'), ('FIRMADO', 'Firmado'), ('ENVIADO', 'Enviado a SUNAT'), ('ACEPTADO', 'Aceptado por SUNAT'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error en Procesamiento')], default='BORRADOR', max_length=20)),
                ('datos_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Electrónico',
                'verbose_name_plural': 'Documentos Electrónicos',
                'db_table': 'documentos_electronicos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener exactamente 11 dígitos', regex='^\\d{11}$')])),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField()),
                ('ubigeo', models.CharField(blank=True, max_length=6, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='DocumentoLinea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_linea', models.IntegerField()),
                ('codigo_producto', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(default='NIU', max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=10, max_digits=12)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('afectacion_igv', models.CharField(choices=[('10', 'Gravado - Operación Onerosa'), ('11', 'Gravado - Retiro por premio'), ('12', 'Gravado - Retiro por donación'), ('20', 'Exonerado - Operación Onerosa'), ('30', 'Inafecto - Operación Onerosa'), ('40', 'Exportación')], default='10', max_length=2)),
                ('igv_linea', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('isc_linea', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('icbper_linea', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='documentos.documentoelectronico')),
            ],
            options={
                'verbose_name': 'Línea de Documento',
                'verbose_name_plural': 'Líneas de Documento',
                'db_table': 'documento_lineas',
                'ordering': ['numero_linea'],
            },
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentos.empresa'),
        ),
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo_pfx', models.FileField(upload_to='certificados/')),
                ('password_hash', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='documentos.empresa')),
            ],
            options={
                'verbose_name': 'Certificado Digital',
                'verbose_name_plural': 'Certificados Digitales',
                'db_table': 'certificados_digitales',
            },
        ),
        migrations.CreateModel(
            name='LogOperacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operacion', models.CharField(choices=[('CONVERSION', 'Conversión a UBL'), ('FIRMA', 'Firma Digital'), ('ENVIO', 'Envío a SUNAT'), ('VALIDACION', 'Validación')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duracion_ms', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documentos.documentoelectronico')),
            ],
            options={
                'verbose_name': 'Log de Operación',
                'verbose_name_plural': 'Logs de Operaciones',
                'db_table': 'logs_operaciones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento'),
        ),
        migrations.AlterUniqueTogether(
            name='documentoelectronico',
            unique_together={('empresa', 'tipo_documento', 'serie', 'numero')},
        ),
    ]
