# Generated by Django 5.2.4 on 2025-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_add_missing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoelectronico',
            name='correlation_id',
        ),
        migrations.RemoveField(
            model_name='documentoelectronico',
            name='last_sunat_response',
        ),
        migrations.RemoveField(
            model_name='documentoelectronico',
            name='numero_ticket',
        ),
        migrations.RemoveField(
            model_name='logoperacion',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='logoperacion',
            name='resultado',
        ),
        migrations.AlterField(
            model_name='documentoelectronico',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Firma'), ('FIRMADO', 'Firmado'), ('FIRMADO_SIMULADO', 'Firmado Simulado'), ('ENVIADO', 'Enviado a SUNAT'), ('ACEPTADO', 'Aceptado por SUNAT'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error en Procesamiento')], default='BORRADOR', max_length=20),
        ),
    ]
